/**
 * End-to-end walk through the periodical workflow: import a PDF newspaper with
 * an issue date, read it with a real text layer, look up an English and a
 * Malayalam word, and confirm excerpts are filed on a page of their own for
 * that issue date.
 *
 *   npm run test:e2e
 *
 * Requires the server to be running (npm start). The fixture is generated by
 * e2e/fixtures/make-newspaper.mjs.
 */
import { BASE, openBrowser, makeStep, finish } from './helpers.mjs';

const PDF = process.env.READIT_SAMPLE_PDF ?? new URL('./fixtures/kerala-chronicle-2026-03-04.pdf', import.meta.url).pathname;

const { browser, page: p, errors } = await openBrowser();
const { step } = makeStep();

await step('upload as a newspaper with an issue date', async()=>{
  await p.goto(BASE,{waitUntil:'networkidle'});
  await p.click('text=+ Add to library');
  await p.setInputFiles('input[type=file]', PDF);
  const dlg = p.locator('[role=dialog]');
  await dlg.locator('summary').click();
  await dlg.locator('select').first().selectOption('newspaper');
  await dlg.locator('input[type=date]').first().fill('2026-03-04');
  await dlg.locator('input[placeholder="Politics, Non-fiction"]').fill('News, Politics');
  await p.click('button:has-text("Import")');
  await p.waitForSelector('a:has-text("Kerala Chronicle")', {timeout:60000});
});

await step('newspaper facet appears', async()=>{
  await p.waitForSelector('aside button:has-text("Newspaper")',{timeout:15000});
  await p.waitForSelector('aside button:has-text("News")',{timeout:15000});
});

await step('open the newspaper', async()=>{
  await p.click('a:has-text("Kerala Chronicle")');
  await p.waitForSelector('h1');
  const dl=await p.textContent('dl');
  if(!dl.includes('2026-03-04')) throw new Error('issue date missing: '+dl.slice(0,200));
});
const itemId=Number(p.url().split('/').pop());

await step('PDF renders with a selectable text layer', async()=>{
  await p.goto(`${BASE}/read/${itemId}`,{waitUntil:'networkidle'});
  await p.waitForSelector('.pdf-page canvas',{timeout:60000});
  await p.waitForFunction(()=>document.querySelectorAll('.textLayer span').length>20,null,{timeout:60000});
  const pages=await p.locator('.pdf-page').count();
  if(pages<2) throw new Error(`expected a multi-page PDF, got ${pages}`);
});

await step('selecting an English word in the PDF looks it up', async()=>{
  await p.evaluate(()=>{
    const span=[...document.querySelectorAll('.textLayer span')].find(s=>/corruption/i.test(s.textContent));
    const node=span.firstChild; const i=span.textContent.search(/corruption/i);
    const r=document.createRange(); r.setStart(node,i); r.setEnd(node,i+10);
    const s=window.getSelection(); s.removeAllRanges(); s.addRange(r);
    document.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));
  });
  await p.waitForSelector('[role=dialog][aria-label=Selection]',{timeout:10000});
  const t=await p.textContent('[role=dialog][aria-label=Selection]');
  if(!/wordnet/i.test(t)) throw new Error('no definition: '+t.slice(0,150));
});

await step('selecting a Malayalam word looks it up in Sabdatharavali', async()=>{
  // pdf.js splits Malayalam into one span per glyph run, so a real mouse drag
  // spans several elements. Reproduce that rather than selecting inside one.
  const picked = await p.evaluate(()=>{
    const spans=[...document.querySelectorAll('.textLayer span')];
    for(let i=0;i<spans.length;i++){
      for(let j=i;j<Math.min(i+6,spans.length);j++){
        const joined=spans.slice(i,j+1).map(s=>s.textContent).join('');
        if(joined.replace(/\s+/g,'')==='\u0d15\u0d35\u0d3f\u0d24'){
          const r=document.createRange();
          r.setStartBefore(spans[i]); r.setEndAfter(spans[j]);
          const sel=window.getSelection(); sel.removeAllRanges(); sel.addRange(r);
          document.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));
          return sel.toString();
        }
      }
    }
    return null;
  });
  if(!picked) throw new Error('Malayalam word not found across the text layer spans');
  await p.waitForSelector('[role=dialog][aria-label=Selection]',{timeout:10000});
  const t=await p.textContent('[role=dialog][aria-label=Selection]');
  if(!/poem/i.test(t)) throw new Error('Malayalam lookup failed for '+JSON.stringify(picked)+': '+t.slice(0,200));
  console.log('\n    ML popup:', t.replace(/\s+/g,' ').slice(0,140)); process.stdout.write('  ');
});


await step('save the Malayalam word', async()=>{
  await p.click('button:has-text("Save word")');
  await p.waitForSelector('text=Saved to the word list',{timeout:10000});
});

await step('add an excerpt — it files under the issue date', async()=>{
  await p.evaluate(()=>{
    const spans=[...document.querySelectorAll('.textLayer span')].slice(6,14);
    const r=document.createRange(); r.setStartBefore(spans[0]); r.setEndAfter(spans[spans.length-1]);
    const s=window.getSelection(); s.removeAllRanges(); s.addRange(r);
    document.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));
  });
  await p.waitForSelector('[role=dialog][aria-label=Selection]',{timeout:10000});
  await p.click('button:has-text("Add to notes")');
  await p.waitForSelector('text=Added to reading notes',{timeout:10000});
  await p.click('a[title="Reading notes"]');
  await p.waitForSelector('article');
  const pageTitle=await p.locator('section input').first().inputValue();
  if(pageTitle!=='Issue of 2026-03-04') throw new Error('page not titled by issue date: '+pageTitle);
  const sec=await p.textContent('section');
  if(!sec.includes('2026-03-04')) throw new Error('issue date not shown on the page: '+sec.slice(0,160));
  const t=await p.textContent('h1');
  if(!t.includes('2026-03-04')) throw new Error('document title lacks the issue date: '+t);
});

await browser.close();
finish(errors, 'Periodical workflow');
